<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title><?= $this->escape($this->meta_title) ?></title>
        <meta name="keywords" content="<?= $this->escape($this->meta_keywords) ?>"/> 
        <meta name="description" content="<?= $this->escape($this->meta_description) ?>"/>
        <link rel="stylesheet" href="/css/index.css" />
        <link rel="stylesheet" href="/css/rouble/stylesheet.css" />
        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery.lazyload.min.js"></script>
        <script src="/js/interface.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <div class="logo">
                    <a href="/"></a>
                </div>
                <div class="search">
<?= $this->search ?>
                </div>
                <div class="contact">
<?= $this->header_contact ?>
                </div>
                <div class="info">
<?= $this->cart ?>
                </div>
            </header>
            
            <div class="content">
                <nav>
<?= $this->menu ?>
                </nav>

<?php if ($this->teaser) { ?>
<?= $this->teaser ?>

<?php } ?>
                <aside>
<?= $this->catalogue ?>
                </aside>

                <article>
<?php if ($this->marker) { ?>
<?= $this->marker ?>

<?php } ?>
<?= $this->content ?>
                </article>
            </div>
            
            <footer>
                <div class="copyright">
<?= $this->copyright ?>
                </div>
                <div class="address">
<?= $this->address ?>
                </div>
                <div class="contact">
<?= $this->footer_contact ?>
                </div>
            </footer>
        </div>
        
        <a id="up-arrow" href=""></a>
        
        <!-- BEGIN JIVOSITE CODE {literal} -->
        <script type='text/javascript'>
            (function(){ var widget_id = 'lH28WBfCYG'; var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);})();
        </script>
        <!-- {/literal} END JIVOSITE CODE --> 
    </body>
</html>
