                    <h1><?= $this->catalogue->getCatalogueTitle() ?></h1>
<?php if ($this->catalogue->getCatalogueDescription()) { ?>
<?= $this->catalogue->getCatalogueDescription() ?>
<?php } ?>
                    <div class="catalogue_list">
<?php foreach ($this->catalogue_list as $catalogue_item) { ?>
                        <div class="catalogue_item">
                            <div class="image">
                                <a href="<?= $catalogue_item->getCatalogueUrl() ?>">
                                    <img class="lazy" data-original="<?= $catalogue_item->getCatalogueImage() . '/r/170/170' ?>" />
                                </a>
                            </div>
                            <div class="title">
                                <a href="<?= $catalogue_item->getCatalogueUrl() ?>"><?= $catalogue_item->getCatalogueTitle() ?></a>
                            </div>
                        </div>
<?php } ?>
                    </div>
