                    <h1>Регистрация для оптовых покупателей</h1>
                    <p>Если Вы хотите работать с нашей компанией на постоянной основе, заполните анкету на данной странице. В ответ наш менеджер вышлет Вам информацию об условиях сотрудничества и актуальный прайс-лист.</p>
                    <form method="post">
                       <div class="field">
                            Ваше имя: <span class="require">*</span><br />
                            <input type="text" value="<?= $this->escape($this->fromRequest('subscribe_person')) ?>" name="subscribe_person" />
<?php if ($this->error['subscribe_person']) { ?>
                            <span class="error"><?= $this->error['subscribe_person'] ?></span>
<?php } ?>
                        </div>
                        <div class="field">
                            Ваш email: <span class="require">*</span><br />
                            <input type="text" value="<?= $this->escape($this->fromRequest('subscribe_email')) ?>" name="subscribe_email" />
<?php if ($this->error['subscribe_email']) { ?>
                            <span class="error"><?= $this->error['subscribe_email'] ?></span>
<?php } ?>
                        </div>
                        <div class="field">
                            Название компании (для юрлиц):<br />
                            <input type="text" value="<?= $this->escape($this->fromRequest('subscribe_company')) ?>" name="subscribe_company" />
<?php if ($this->error['subscribe_company']) { ?>
                            <span class="error"><?= $this->error['subscribe_company'] ?></span>
<?php } ?>
                        </div>
                        <div class="field">
                            Тип компании (для юрлиц обязательно):<br />
                            <select name="subscribe_type">
                                <option value=""></option>
<?php foreach ($this->type_list as $value => $title) { ?>
                                <option value="<?= $value ?>"<? if ($this->inRequest('subscribe_type', $value)) { ?> selected="selected"<? } ?>><?= $title ?></option>
<?php } ?>
                            </select>
<?php if ($this->error['subscribe_type']) { ?>
                            <span class="error"><?= $this->error['subscribe_type'] ?></span>
<?php } ?>
                        </div>
                        <div class="field">
                            Телефон (для юрлиц обязательно):<span class="require">*</span><br />
                            <input type="text" value="<?= $this->escape($this->fromRequest('subscribe_phone')) ?>" name="subscribe_phone" />
<?php if ($this->error['subscribe_phone']) { ?>
                            <span class="error"><?= $this->error['subscribe_phone'] ?></span>
<?php } ?>
                        </div>
                        <div class="field captcha">
                            Введите символы с картинки: <span class="require">*</span><br />
                            <img src="/image/captcha.php" />
                            <input type="text" name="subscribe_captcha" value="" autocomplete="no" />
<?php if ($this->error['subscribe_captcha']) { ?>
                            <span class="error"><?= $this->error['subscribe_captcha'] ?></span>
<?php } ?>
                            <br/><br/>
                        </div>
                        <div class="field">
                            <input type="submit" value="Зарегистрироваться" class="button" />
                        </div>
                    </form>
