<p>Заказ №<?= $this->purchase->getId() ?></p>

<p>
<?php $item_index = 1; ?>
<?php foreach ($this->purchase->getItemList() as $purchase_item) { ?>
<?php 	$product = Adminko\Model\Model::factory('product')->get($purchase_item->getItemProduct()); ?>
<?= $item_index ?>. <?= $product->getProductTitle() ?> x <?= $purchase_item->getItemQuantity() ?> шт.<br/>
<?php   $item_index++; ?>
<?php } ?>
</p>

<p>Общая стоимость заказа: <?= $this->purchase->getPurchaseSum() ?> р.</p>

<p>
Контактное лицо: <?= $this->purchase->getPurchasePerson() ?><br/>
Email: <?= $this->purchase->getPurchaseEmail() ?><br/>
Телефон: <?= $this->purchase->getPurchasePhone() ?><br/>
Адрес: <?= $this->purchase->getPurchaseAddress() ?><br/>
Комментарий: <?= $this->purchase->getPurchaseComment() ?>
</p>

<p>Перейти к редактированию заказов <a href="http://ganteli-shtangi.ru/admin/purchase">http://ganteli-shtangi.ru/admin/purchase</a>.</p>
