                <h1>Корзина</h1>
<?php if ($this->getQuantity()) { ?>
                <script type="text/javascript" src="/js/jquery.form.js"></script>

                <form id="cart" method="post" action="/cart/save">
                    <table class="cart">
                        <tr>
                            <td colspan="2">
                                Ваш заказ
                            </td>
                            <td>
                                Цена
                            </td>
                            <td>
                                Кол-во
                            </td>
                            <td>
                                Стоимость
                            </td>
                            <td>
                                &nbsp;
                            </td>
                        </tr>
<?php 		foreach ($this->get() as $item) { ?>
<?php 			$product_item = Adminko\Model\Model::factory('product')->get($item->id); ?>
                        <tr>
                            <td class="image">
                                <a href="/">
                                    <img src="<?= $product_item->getProductImage() . '/c/50/50' ?>" />
                                </a>
                            </td>
                            <td class="product">
                                <a href="<?= $product_item->getProductUrl() ?>"><?= $product_item->getProductTitle() ?></a>
                            </td>
                            <td class="price">
                                <?= number_format($item->price, 0, 0, ' ') ?> <span class="rouble">Р</span>
                            </td>
                            <td class="quantity">
                                <input type="hidden" value="<?= $item->price ?>" name="price[<?= $item->id ?>]"/>
                                <a href="" onclick="incItem($(this)); return false" class="plus"></a>
                                <input type="text" value="<?= $item->quantity ?>" name="quantity[<?= $item->id ?>]" readonly="readonly" class="quantity"/>
                                <a href="" onclick="decItem($(this)); return false" class="minus"></a>
                            </td>
                            <td class="cost">
                                <?= number_format($item->price * $item->quantity, 0, 0, ' ') ?> <span class="rouble">Р</span>
                            </td>
                            <td class="delete">
                                <a class="delete" href="/cart/delete/<?= $item->id ?>" title="Удалить">
                                    Удалить
                                </a>
                            </td>
                        </tr>
<?php 		} ?>
                        <tr>
                            <td colspan="2">
                                &nbsp;
                            </td>
                            <td class="total">
                                Итого:
                            </td>
                            <td class="quantity">
                                <?= $this->getQuantity() ?>
                            </td>
                            <td class="cost">
                                <?= number_format($this->getSum(), 0, 0, ' ') ?> <span class="rouble">Р</span>
                            </td>
                            <td class="delete">
                                &nbsp;
                            </td>
                        </tr>
                    </table>
                </form>
                <br/>
                <input type="button" value="Оформить заказ" onclick="window.location.href = '/purchase'" class="button" />
                &nbsp;&nbsp;&nbsp;
                <input type="button" value="Очистить корзину" onclick="if ( confirm('Вы уверены, что хотите очистить корзину?') ) { window.location.href = '/cart/clear'; }" class="button" />
<?php } else { ?>
                <h3>Ваша корзина пуста</h3>
<?php } ?>
